% function r = admTransformParameters(name1, value1, name2, value2, ...)
%
% see also admOptions
%
% This file is part of the ADiMat runtime environment.
%
% Copyright 2009-2011 Johannes Willkomm, Institute for Scientific Computing
% Copyright 2001-2009 Andre Vehreschild, Institute for Scientific Computing
%                     RWTH Aachen University
function r = admTransformParameters(varargin)
r = struct('admTransformParameters', 1, ...
           'gzerosfunction', 'g_', ...
           'gradprefix', 'g_', ...
           'hessprefix', 'h_', ...
           'funcprefix', 'g_', ...
           'exportcgvcg', '', ...
           'exportcgsimp', '', ...
           'exportcgtxt', '', ...
           'sndorderfwd', 0, ...
           'secondorderfwd', 0, ...
           'nocanonicalize', '', ...
           'noAD', 0, ...
           'noforwardvarresolv', 0, ...
           'nobuiltins', 0, ...
           'nolocalmfiles', 0, ...
           'nooperoptim', 0, ...
           'nolocalcse', 0, ...
           'noglobalcse', 0, ...
           'globalcse', 0, ...
           'noloopsaving', 0, ...
           'nooverwrtchk', 0, ...
           'noscalarfolding', 0, ...
           'noprescalarfolding', 0, ...
           'nopostscalarfolding', 0, ...
           'noconstfoldmult0', 0, ...
           'nonargsupport', 0, ...
           'notmpclear', 0, ...
           'nosigensure', 0, ...
           'diffifcond', 0, ...
           'noforwardvarsubs', 0, ...
           'nouservarforsubs', 0, ...
           'nobracketsopt', 0, ...
           'aZerosFunction', '', ...
           'activityAnalysis', '', ...
           'adimatFunctionPrefix', '', ...
           'adjointReductions', '', ...
           'adjointReshapes', '', ...
           'allowArrayGrowth', '', ...
           'avoidVarargFunctions', '', ...
           'commentChar', '', ...
           'commentSpacer', '', ...
           'commentStart', '', ...
           'fm', '', ...
           'fmmode', '', ...
           'forwardDerivFunctionPrefix', '', ...
           'forwardDerivVariablePrefix', '', ...
           'from', '', ...
           'indToSubsDeep', '', ...
           'indentUnit', '', ...
           'inputFileName', '', ...
           'noMissingAdjointArgs', '', ...
           'outputDirectory', '', ...
           'outputFilePath', '', ...
           'outputFilePrefix', '', ...
           'outputMode', '', ...
           'parallel', '', ...
           'parallelFunctionPrefix', '', ...
           'prefix', '', ...
           'printStackInfo', '', ...
           'recPrefix', '', ...
           'retPrefix', '', ...
           'revPrefix', '', ...
           'showBanner', '', ...
           'showDisclaimer', '', ...
           'showStepIds', '', ...
           'showStepParams', '', ...
           'showSteps', '', ...
           'sourceLineNumbers', '', ...
           'stackInfoFunction', '', ...
           'subsrefFunctionPrefix', '', ...
           'tmpMode', '', ...
           'tmpPrefix', '', ...
           'to', '', ...
           'useAdjsum', '', ...
           'usePushIndex', '', ...
           'useSubsasgn', '', ...
           'useSubsref', '', ...
           'wellBehaved', '');
