function times = admTimes()
  times = struct('necessity_check', 0, 'dependency_check', 0, ...
                 'transformation', 0, 'wait', 0, 'evaluation', 0, ...
                 'seeding', 0, 'total', 0, 'message', '');
% $Id: admTimes.m 2822 2011-04-06 12:16:52Z willkomm $
